name: Days until GTA 6

on:
  schedule:
    - cron: '0 0 * * 1-5'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  make-contribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: days left to GTA 6
        run: |
          target="2026-11-19"
          today="$(date +%Y-%m-%d)"
          days_left=$(( ( $(date -d "$target" +%s) - $(date -d "$today" +%s) ) / 86400 ))
          echo -e "<div align='center'><img alt='Days until gta6' src='media/days_until_gta6.jpg'><h1>Today is $today and there are $days_left days until GTA 6.</h1><div/>" > README.md
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          commit_message: updated date
